apiVersion: v1
kind: ConfigMap
metadata:
  name: learn2earn-config
  namespace: learn2earn
data:
  DEBUG: "0"
  ALLOWED_HOSTS: "api.learn2earn.local"
  CORS_ALLOWED_ORIGINS: "https://app.learn2earn.local"
  SOROBAN_RPC_URL: "https://soroban-testnet.stellar.org"
  HORIZON_URL: "https://horizon-testnet.stellar.org"
  STELLAR_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
