apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learn2earn
  namespace: learn2earn
spec:
  ingressClassName: nginx
  rules:
    - host: api.learn2earn.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learn2earn-backend
                port:
                  number: 80
