apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: learn2earn-secrets
  namespace: learn2earn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: learn2earn-secrets
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: learn2earn/SECRET_KEY
    - secretKey: DATABASE_URL
      remoteRef:
        key: learn2earn/DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: learn2earn/REDIS_URL
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: learn2earn/CELERY_BROKER_URL
    - secretKey: CELERY_RESULT_BACKEND
      remoteRef:
        key: learn2earn/CELERY_RESULT_BACKEND
    - secretKey: LEARN2EARN_CONTRACT_ID
      remoteRef:
        key: learn2earn/LEARN2EARN_CONTRACT_ID
    - secretKey: INDEXER_SECRET_KEY
      remoteRef:
        key: learn2earn/INDEXER_SECRET_KEY
